ALTER TABLE ARTICULO
ALTER COLUMN ID_PROVEEDOR INT;

ALTER TABLE PROVEEDOR
ALTER COLUMN ID_PROVEEDOR INT;


SELECT ID_SUCURSAL, ARTICULO, SUM(VENTAS) AS VENTAS_TOTALES_X_ARTICULO
FROM [Control Ventas]
GROUP BY ID_SUCURSAL, ARTICULO
ORDER BY SUM(VENTAS) DESC

SELECT NOMBRE_ARTICULO, SUM(TOTAL_ARTICULO_DISPONIBLE) AS TOTAL
FROM [Control Inventario]
WHERE  ULTILMA_ACTUALIZACION = (SELECT MAX(ULTILMA_ACTUALIZACION) FROM [Control Inventario])

GROUP BY NOMBRE_ARTICULO
ORDER BY SUM(TOTAL_ARTICULO_DISPONIBLE) DESC



CREATE VIEW AUX2 AS 
SELECT E.NOMBRE, E.SUCURSAL_REGISTRO, CI.NOMBRE_ARTICULO, CI.TOTAL_ARTICULO_DISPONIBLE, S.NOMBRE_OFICIAL
FROM Empleado AS E 
INNER JOIN 
     [Control Inventario] AS CI 
	 ON E.ID_EMPLEADO = CI.EMPLEADO_RESPONSABLE
INNER JOIN 
     Sucursal AS S
	 on E.SUCURSAL_REGISTRO = S.ID_SUCURSAL

SELECT TOP 1 NOMBRE, SUCURSAL_REGISTRO, NOMBRE_OFICIAL, SUM(TOTAL_ARTICULO_DISPONIBLE) AS TOTAL_ARTICULO
FROM AUX2
GROUP BY NOMBRE, SUCURSAL_REGISTRO, NOMBRE_OFICIAL
ORDER BY SUM(TOTAL_ARTICULO_DISPONIBLE) DESC


SELECT TOP 1 NOMBRE, MAX(EDAD) AS EDAD_MAXIMA
FROM EMPLEADO
GROUP BY NOMBRE
ORDER BY EDAD_MAXIMA DESC




